config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'visitors/index'

  root to: 'visitors#index'
  resources :visitors

  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: 'registrations' } do
    match 'users/sign_out', to: 'devise/sessions#destroy', via: :delete
  end
  resources :users do
    match '/new_gallery', to: 'users#new_gallery', via: :get
    match '', to: 'users#create_gallery', via: :patch
  end

  resources :attachments do
    member do
      post 'like'
      post 'dislike'
    end
  end
  get 'all_attachments', to: 'attachments#all_attachments'
  get '/:id/show_gallery', to: 'attachments#show_gallery', as: 'gallery'
  resources :roles
  resources :orders
  get '/orders/confirm_order', to: 'orders#confirm_order'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attachment.rb
# frozen_string_literal: true

class Attachment < ApplicationRecord
  belongs_to :user
  has_many :reactions

  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :image_type, presence: true
  validates :place, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :created_by, presence: true
  validates :image, presence: true, file_size: { less_than: 1.megabyte }

  def update_attachment_after_order(amount)
    if update(amount: amount)
      puts 'success'
    else
      puts 'failed to update amount'
    end
  end

  def already_liked(attachment, current_user)
    return false unless already_reacted(attachment, current_user)

    Reaction.where(user_id: current_user.id, attachment_id: attachment.id).first.like?
  end

  def already_disliked(attachment, current_user)
    return false unless already_reacted(attachment, current_user)

    Reaction.where(user_id: current_user.id, attachment_id: attachment.id).first.dislike?
  end

  def already_reacted(attachment, current_user)
    Reaction.where(user_id: current_user.id, attachment_id: attachment.id).exists?
  end
end

app/controllers/attachments_controller.rb
# frozen_string_literal: true

class AttachmentsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!, except: %i[all_attachments show show_gallery]

  def index; end

  def like
    respond_to do |format|
      if @attachment.already_reacted(@attachment, current_user)
        @reaction = Reaction.where(user_id: current_user.id, attachment_id: @attachment.id)
        if @reaction.update(user: current_user, attachment: @attachment, status: params[:status], reaction: params[:reaction])
          format.html { redirect_back fallback_location: all_attachments_path, notice: 'you liked an attachment.' }
          format.js
        else
          format.html { redirect_back fallback_location: all_attachments_path, alert: 'An error preventing you from liking this attachment.' }
          format.js
        end
      else
        @reaction = Reaction.create(user: current_user, attachment: @attachment, status: params[:status], reaction: params[:reaction])
        if @reaction.save
          format.html { redirect_back fallback_location: all_attachments_path, notice: 'you liked an attachment.' }
          format.js
        else
          format.html { redirect_back fallback_location: all_attachments_path, alert: 'An error preventing you from liking this attachment.' }
          format.js
        end
      end
    end
  end

  def dislike
    respond_to do |format|
      if @attachment.already_reacted(@attachment, current_user)
        @reaction = Reaction.where(user_id: current_user.id, attachment_id: @attachment.id)
        if @reaction.update(user: current_user, attachment: @attachment, status: params[:status], reaction: params[:reaction])
          format.html { redirect_back fallback_location: all_attachments_path, notice: 'you disliked an attachment.' }
          format.js
        else
          format.html { redirect_back fallback_location: all_attachments_path, alert: 'An error preventing you from disliking this attachment.' }
          format.js
        end
      else
        @reaction = Reaction.create(user: current_user, attachment: @attachment, status: params[:status], reaction: params[:reaction])
        if @reaction.save
          # TODO: Move hardcode flash message into language file
          format.html { redirect_back fallback_location: all_attachments_path, notice: 'you disliked an attachment.' }
          format.js
        else
          format.html { redirect_back fallback_location: all_attachments_path, alert: 'An error preventing you from disliking this attachment.' }
          format.js
        end
      end
    end
  end

  def all_attachments
    @users = User.all
    @attachments = Attachment.left_outer_joins(:reactions).group(:id).order('count(*) desc')
  end

  def show_gallery
    @user = current_user
    @user_id = Attachment.select(:user_id).where(id: params[:id])
    @attachments = Attachment.where(user_id: @user_id)
  end

  def show
    @attachment = Attachment.find(params[:id])
  end

  def new
    @attachment = Attachment.new
  end

  def edit
    @attachment = Attachment.find(params[:id])
  end

  def create
    @attachment = current_user.attachments.create(attachment_params)
    respond_to do |format|
      if @attachment.save
        # TODO: Move hardcode flash message into language file
        format.html { redirect_to attachment_path(@attachment), notice: 'Attachment was successfully added.' }
      else
        format.html { render :new, alert: 'Attachments could not be added.' }
      end
    end
  end

  def update
    @attachment = Attachment.find(params[:id])
    respond_to do |format|
      if @attachment.update(attachment_params)
        # TODO: Move hardcode flash message into language file
        format.html { redirect_to attachment_path(@attachment), notice: 'Attachment was successfully updated.' }
      else
        format.html { render :edit, alert: 'Attachments could not be updated.' }
      end
    end
  end

  def destroy
    @attachment = current_user.attachments.find(params[:id])
    @attachment.destroy

    redirect_to attachments_path
  end

  private

  def attachment_params
    params.require(:attachment).permit(:title, :image_type, :description, :price, :created_by, :place, :user_id, :image_cache, :remote_image_url, :image, :images_cache, :remove_image, :amount)
  end
end

app/helpers/attachments_helper.rb
# frozen_string_literal: true

module AttachmentsHelper
  def check_for_user_like(attachment)
    if user_signed_in?
      return true if attachment.already_liked(attachment, current_user)

      return false
    end
    false
  end

  def show_gallery_image(user)
    user.attachments.last.image.large_thumb.url
  end
end

app/views/attachments/_attachment.html.erb
<div class="row mb-1 align-items-center text-center">
<div class="col-md-2"><%= attachment.title %></div>
<div class="col-md-2"> <%= attachment.amount %></div>
<div class="col-md-3"><%= image_tag attachment.image.small_thumb.url if attachment.image? %></div>
<div class="col-md-5">
    <%= link_to 'Show', attachment, class: 'btn btn-success' %>
    <%= link_to 'Edit', edit_attachment_path(attachment), class: 'btn btn-info' %> 
	<%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>
</div>

app/views/attachments/_create_attachment.html.erb
<div class="form-group">
	<strong><%= f.label :title %></strong>
	<%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
 	<strong><%= f.label :description %></strong>
 	<%= f.text_area :description, class: "form-control" %>
</div>

<div class="form-group">
 	<strong><%= f.label :image_type %></strong>
 	<%= f.text_field :image_type, class: "form-control" %>
</div>

<div class="form-group">
 	<strong><%= f.label :place %></strong>
 	<%= f.text_field :place, class: "form-control" %>
</div>

<div class="form-group">
 	<strong><%= f.label :created_by %></strong>
 	<%= f.text_field :created_by, class: "form-control" %>
</div>

<div class="form-group">
 	<strong><%= f.label :price %></strong>
 	<%= f.text_field :price, class: "form-control" %>
</div>
<div class="form-group">
 	<strong><%= f.label :amount %></strong>
 	<%= f.text_field :amount, class: "form-control" %>
</div>
<div class="form-group">
 	<strong><%= f.label :image %></strong>
 		<br>
 		<%= f.file_field :image %>
 		<%= f.hidden_field :image_cache %>
 		<br>
 		<strong><%= label_tag "Enter Url of Image" %></strong>
 		<%= f.text_field :remote_image_url, class: "form-control" %>
</div>

app/views/attachments/_form.html.erb
<%= form_for(attachment) do |f| %>

	<%= render partial: 'errors', locals: { attachment: attachment } %>

	<div class="form-group">
		<strong><%= f.label :title %></strong>
		<%= f.text_field :title, class: "form-control" %>
	</div>

	<div class="form-group">
	 	<strong><%= f.label :description %></strong>
	 	<%= f.text_area :description, class: "form-control" %>
	</div>

	<div class="form-group">
	 	<strong><%= f.label :image_type %></strong>
	 	<%= f.text_field :image_type, class: "form-control" %>
	</div>

	<div class="form-group">
	 	<strong><%= f.label :place %></strong>
	 	<%= f.text_field :place, class: "form-control" %>
	</div>

	<div class="form-group">
	 	<strong><%= f.label :created_by %></strong>
	 	<%= f.text_field :created_by, class: "form-control" %>
	</div>

	<div class="form-group">
	 	<strong><%= f.label :price %></strong>
	 	<%= f.text_field :price, class: "form-control" %>
	</div>

	<div class="form-group">
	 	<strong><%= f.label :Add_Amount %></strong>
	 	<%= f.text_field :amount, class: "form-control" %>
	</div>

	<div class="form-group">
	 	<strong><%= f.label :image %></strong>
	 	<div class="form-group"> 
	 		<%= f.file_field :image %>
	 		<%= f.hidden_field :image_cache %>
	 		<br><br>
	 		<strong><%= label_tag "Enter Url of Image" %></strong>
	 		<%= f.text_field :remote_image_url, class: "form-control" %>
	 	</div>
	 	<div class="form-group">
	 		<% if attachment.image? %>
	 			<%= image_tag attachment.image.thumb.url %>
	 			<div>
	 				<%= label_tag ":remove_image" do %>
	 					Remove Image
	 					<%= f.check_box :remove_image %>
	 				<% end %>
	 			</div>
	 		<% end %>
		</div>
	</div>

	<div>
		<%= f.submit class: "btn btn-primary"%>
	</div>

<% end %>

app/views/attachments/_reaction-count.html.erb
<div>
	likes: <%= @attachment.reactions.likes.count %>
</div>

app/views/attachments/_show_attachment.html.erb
<div class="container">
  <% if @attachment.amount < 1 %>
    <div class="alert alert-warning"> Out of Stock now </div>
  <% end %>
  <br>
  <div class="row">
    <div class="col-sm-3">
      <% if @attachment.image %>
        <div class="image-text">
          <%= image_tag(@attachment.image.thumb.url, alt: 'Image') %>
          <div class="centered">
            <%= link_to "Show image" , @attachment.image.url, target: "_blank", class: "btn-image" %>
          </div>
          <div id="js-reaction-count">
            <%= render 'reaction-count' %>
          </div>
        </div>      
      <% end %>
      <hr>
      <div class="row">
        <% if check_for_user_like(@attachment) %>
            <div id="js-like-section" class="col-md-4 hidden">
              <%= link_to 'like', like_attachment_path(@attachment, status: 'like', reaction: true), remote: true, method: 'post', class: 'btn btn-info' %>
            </div>
            <div id="js-dislike-section" class="col-md-4">
              <%= link_to 'dislike', dislike_attachment_path(@attachment, status: 'dislike', reaction: true), remote: true, method: 'post', class: 'btn btn-info' %>
            </div>
        <% else %>
            <div id="js-like-section" class="col-md-4">
              <%= link_to 'like', like_attachment_path(@attachment, status: 'like', reaction: true), remote: true, method: 'post', class: 'btn btn-info' %>
            </div>
            <div id="js-dislike-section" class="col-md-4 hidden">
              <%= link_to 'dislike', dislike_attachment_path(@attachment, status: 'dislike', reaction: true), remote: true, method: 'post', class: 'btn btn-info' %>
            </div>
        <% end %>
      </div>
      <hr>
    </div>
    <div class="col-sm-9">
      <div>
        <strong>Title:</strong>
        <%= @attachment.title %>
      </div>
      <div>
        <strong>Description:</strong>
        <%= @attachment.description %>
      </div>
      <div>
        <strong>type:</strong>
        <%= @attachment.image_type %>
      </div>
      <div>
        <strong>place:</strong>
        <%= @attachment.place %>
      </div>
      <div>
        <strong>Created By:</strong>
        <%= @attachment.created_by %>
      </div>
      <div>
        <strong>price:</strong>
        <%= @attachment.price %>
      </div>
      <div>
        <% if user_signed_in? && current_user.id == @attachment.user_id %>
        <strong>Amount:</strong>
        <%= @attachment.amount %>
        <% end %>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-1">
          <%= link_to 'Back', url_for(:back), class: 'back-btn' %>
        </div>
        <div class="col-md-1" >
          <% if @attachment.amount > 0 %>
            <%= link_to 'Buy', new_order_path(attachment: @attachment.id), class: 'btn btn-info' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/attachments/all_attachments.html.erb
  <div class="row">
    <div class="col-md-12" id="js-show-attachment">
    </div>
  </div>
      <hr>
  <div class="row">
      <%= render 'all_attachments', locals: { attachments: @attachments} %>
  </div>

app/views/attachments/dislike.js.erb
$("#js-dislike-section").hide();
$("#js-like-section").show();
$("#js-reaction-count").html("<%= j (render 'reaction-count') %>");

app/views/attachments/edit.html.erb
<h1> Edit Attachment </h1>
<div class="authform">
	<%= render partial: 'form', locals: { attachment: @attachment } %>
</div>
<br>
<div>
	<%= link_to 'show', attachment_path(@attachment), class: 'btn btn-info' %>
	<%= link_to 'Back', url_for(:back), class: 'back-btn' %>
</div>

app/views/attachments/index.html.erb
<div class="text-center">
  <h1>Create Gallery</h1>
  <p><strong> User Name:</strong> <%= current_user.username if current_user.username? %> </p>
  <p> Total Attachments: <%= current_user.attachments.count %> </p>
   <p>
    <% if current_user.attachments.any? %>
        <%= link_to "Show Gallery", gallery_path(current_user.attachments.ids), class: 'btn btn-info'%>
      <% end %>
  </p>
</div>
<hr>
<div class="row">
  <div class="col-md-6">
    <h2 class="text-center"> Your Attachments </h2>
    <hr>
    <div class="row text-center">
      <div class="col-md-2">
        <Strong> Title </Strong>
      </div>
      <div class="col-md-2">
        <Strong> Amount </Strong>
      </div>
      <div class="col-md-3">
        <Strong> Image </Strong>
      </div>
    </div>
    <%= render current_user.attachments %>
  </div>
  <div class="col-md-6">
    <div class=" border border-dark p-4 nested-form">
      <h2 class="text-center"> Add New Attachments </h2>
      <hr>
      <%= nested_form_for current_user do |f| %>
        <%= f.fields_for :attachments, Attachment.new do |f| %>
          <div>
            <%= render "attachments/create_attachment", f: f %>
            <hr>
          </div>
        <% end %>
        <div>
          <%= f.link_to_add "Add new Attachment", :attachments, class: "btn btn-info float-right" %>
        </div>
        <div>
          <%= f.submit "Submit" , class: "btn btn-primary"%>
        </div>
      <% end %>
    </div>
  </div>
  <hr>
</div>

app/views/attachments/like.js.erb
$("#js-like-section").hide();
$("#js-dislike-section").show();
$("#js-reaction-count").html("<%= j (render 'reaction-count') %>");

app/views/attachments/new.html.erb
<h1> Add New Attachment </h1>
<div class="authform">
	<%= render partial: 'form', locals: { attachment: @attachment } %>
</div>
<br>
<div><%= link_to 'Back', attachments_path, class: 'back-btn' %></div>

app/views/attachments/show.html.erb
<div class="container">
  <h1> Attachment Showing </h1>
  <% if @attachment.amount < 1 %>
    <div class="alert alert-warning"> Out of Stock now </div>
  <% end %>
  <br>
  <div class="row">
    <div class="col-sm-3">
      <% if @attachment.image %>
        <div class="image-text">
          <%= image_tag(@attachment.image.thumb.url, alt: 'Image') %>
          <div class="centered">
            <%= link_to "Show image" , @attachment.image.url, target: "_blank", class: "btn-image" %>
          </div>
          <div id="reaction-count">
            <%= render 'reaction-count' %>
          </div>
        </div>
      <% end %>
      <hr>
      <div class="row">
      <% if user_signed_in? %>
        <% if @attachment.already_liked(@attachment, current_user) %>
          <div id="like-section" class="col-md-4 hidden">
            <%= link_to 'like', like_attachment_path(@attachment, reaction: true, status: 'like'), remote: true, method: 'post', class: 'btn btn-info' %>
          </div>
          <div id="dislike-section" class="col-md-4">
            <%= link_to 'dislike', dislike_attachment_path(@attachment, reaction: true, status: 'dislike'), remote: true, method: 'post', class: 'btn btn-info' %>
          </div>
        <% else %>
          <div id="like-section" class="col-md-4">
            <%= link_to 'like', like_attachment_path(@attachment, reaction: true, status: 'like'), remote: true, method: 'post', class: 'btn btn-info' %>
          </div>
          <div id="dislike-section" class="col-md-4 hidden">
            <%= link_to 'dislike', dislike_attachment_path(@attachment, reaction: true, status: 'dislike'), remote: true, method: 'post', class: 'btn btn-info' %>
          </div>
        <% end %>
      <% else %>
          <div id="like-section" class="col-md-4">
            <%= link_to 'like', like_attachment_path(@attachment, reaction: true, status: 'like'), remote: true, method: 'post', class: 'btn btn-info' %>
          </div>
          <div id="dislike-section" class="col-md-4">
            <%= link_to 'dislike', dislike_attachment_path(@attachment, reaction: true, status: 'dislike'), remote: true, method: 'post', class: 'btn btn-info' %>
          </div>
      <% end %>
      </div>
      <hr>
      <div>
        <%= link_to 'Show Image', @attachment.image.url, target: "_blank", class: 'btn btn-info' %>
      </div>
    </div>
    <div class="col-sm-9">
      <div>
        <strong>Title:</strong>
        <%= @attachment.title %>
      </div>
      <div>
        <strong>Description:</strong>
        <%= @attachment.description %>
      </div>
      <div>
        <strong>type:</strong>
        <%= @attachment.image_type %>
      </div>
      <div>
        <strong>place:</strong>
        <%= @attachment.place %>
      </div>
      <div>
        <strong>Created By:</strong>
        <%= @attachment.created_by %>
      </div>
      <div>
        <strong>price:</strong>
        <%= @attachment.price %>
      </div>
      <div>
        <% if user_signed_in? && current_user.id == @attachment.user_id %>
        <strong>Amount:</strong>
        <%= @attachment.amount %>
        <% end %>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-1">
          <%= link_to 'Back', url_for(:back), class: 'back-btn' %>
        </div>
        <div class="col-md-1" >
          <% if @attachment.amount > 0 %>
            <%= link_to 'Buy', new_order_path(attachment: @attachment.id), class: 'btn btn-info' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attachments/show.js.erb
$("#js-show-attachment").html("<%= j render 'show_attachment' %>");

app/views/attachments/show_gallery.html.erb
<div class="text-center">
	<h1> Gallery </h1>
	<p> <%= link_to 'back', url_for(:back), class: "back-btn" %> </p>
</div>
<hr>
<div class="row">
	<div class="col-md-12" id="js-show-attachment">
  </div>
</div>
  <hr>
<div class="row">
	<% @attachments.each do |attachment| %>
        <div class="m-1">
        	<div class="image-text">
				<%= image_tag(attachment.image.thumb.url, alt: "image") %>
				<div class="centered">
					<%= link_to "Show" , attachment, class: "btn-image", remote: true %>	
				</div>
			</div>
	    </div>  
    <% end %>
</div>