config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'visitors/index'

  root to: 'visitors#index'
  resources :visitors

  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: 'registrations' } do
    match 'users/sign_out', to: 'devise/sessions#destroy', via: :delete
  end
  resources :users do
    match '/new_gallery', to: 'users#new_gallery', via: :get
    match '', to: 'users#create_gallery', via: :patch
  end

  resources :attachments do
    member do
      post 'like'
      post 'dislike'
    end
  end
  get 'all_attachments', to: 'attachments#all_attachments'
  get '/:id/show_gallery', to: 'attachments#show_gallery', as: 'gallery'
  resources :roles
  resources :orders
  get '/orders/confirm_order', to: 'orders#confirm_order'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_filter :authenticate_user!

  def confirm_order
    @amount = params[:orders][:amount].to_i
    @attachment_amount = params[:attachment_amount].to_i
    @attachment_id = params[:attachment_id].to_i
    @attachment = Attachment.find_by_id(@attachment_id)
  end

  def new
    @attachment = Attachment.find(params[:attachment])
  end

  def create
    @amount = params[:orders][:amount].to_i
    @attachment_amount = params[:attachment_amount].to_i
    @attachment_id = params[:attachment_id].to_i
    @attachment = Attachment.find_by_id(@attachment_id)
    if @amount.zero?
      redirect_back fallback_location: root_path, alert: 'Enter some amount to order.'
    elsif @attachment_amount < @amount
      redirect_back fallback_location: root_path, alert: "Given amount not available. max amount available for this attachment: #{@attachment_amount}"
    else
      @attachment_amount -= @amount
      @attachment.update_attachment_after_order(@attachment_amount)
      redirect_to root_path, notice: 'order was successfully created'
    end
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/orders/new.html.erb
<div class="container">
	<h1 class="text-center"> Order form </h1>
	<hr>
	<div class="row">
		<% if @attachment.amount > 0 %>
			<div class="col-md-3">
				<%= link_to (image_tag @attachment.image.thumb.url), @attachment.image.url %>
			</div>
			<div class="col-md-9">
				<%= form_for :orders, url: '/orders/confirm_order' do |f| %>
					<div class="form-group">
						<%= f.label "Name"%>
						<%= f.text_field :name, class: "form-control" %>
					</div>
					<div class="form-group">
						<%= f.label :amount, "Enter Quantity"%>
						<%= f.text_field :amount, class: "form-control" %>
					</div>
					<div class="form-group">
						<%= f.submit "create order", class: "btn btn-primary" %>
					</div>
					<div>
						<%= link_to "confirm order", orders_confirm_order_path, class: "btn btn-primary" %>
					</div>
					<div>
						<%= hidden_field_tag "attachment_amount", @attachment.amount %>
						<%= hidden_field_tag "attachment_id", @attachment.id %>
					</div>
				<% end %>
			</div>	
		<% else %>
			<div class="alert alert-warning"> sorry, out of stock, come back later </div>
		<% end %>
	</div>
	<div>
		<%= link_to 'back', url_for(:back), class: "back-btn" %>
	</div>
</div>