config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'visitors/index'

  root to: 'visitors#index'
  resources :visitors

  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: 'registrations' } do
    match 'users/sign_out', to: 'devise/sessions#destroy', via: :delete
  end
  resources :users do
    match '/new_gallery', to: 'users#new_gallery', via: :get
    match '', to: 'users#create_gallery', via: :patch
  end

  resources :attachments do
    member do
      post 'like'
      post 'dislike'
    end
  end
  get 'all_attachments', to: 'attachments#all_attachments'
  get '/:id/show_gallery', to: 'attachments#show_gallery', as: 'gallery'
  resources :roles
  resources :orders
  get '/orders/confirm_order', to: 'orders#confirm_order'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles
  validates :name, presence: true
  before_destroy :check_before_destroy

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/controllers/roles_controller.rb
# frozen_string_literal: true

class RolesController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!

  def index
    @roles = Role.all
  end

  def show
    @role = Role.find(params[:id])
  end

  def new
    @role = Role.new
  end

  def edit
    @role = Role.find(params[:id])
  end

  def create
    @role = Role.create(role_params)
    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully added.' }
      else
        format.html { render :new, alert: 'Role not added.' }
      end
    end
  end

  def update
    @role = Role.find(params[:id])
    if @role.update_attributes(role_params)
      redirect_to role_path(@role)
    else
      render :edit
    end
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    redirect_to roles_path
  end

  private

  def role_params
    params.require(:role).permit(:name)
  end
end

app/helpers/roles_helper.rb
# frozen_string_literal: true

module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(role) do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div>
		<%= f.submit class: "btn btn-primary" %>
	</div>
<% end %>

app/views/roles/edit.html.erb
<div class="container">
  <h1> Edit Role </h1>
  <%= render partial: 'form', locals: { role: @role } %>
</div>

app/views/roles/index.html.erb
<div class="container">
	<h1> Roles </h1>
	<hr>
	<div class="row">
		<% @roles.each do |role| %>
			<div class="col-md-2"> <strong> <%= role.name %> </strong> </div>
		<% end %>
	</div>
	<br>
	<%= link_to 'add role', new_role_path, class: 'btn btn-primary' %>
</div>

app/views/roles/new.html.erb
<div class="container">
	<h1> Add New Role </h1>
	<%= render partial: 'form', locals: { role: @role } %>
</div>

app/views/roles/show.html.erb
<h1> Role Showing </h1>
<p>
  <strong>Role :</strong>
  <%= @role.name %>
</p>

<%= link_to 'back to roles', roles_path, class: "back-btn" %>