config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'visitors/index'

  root to: 'visitors#index'
  resources :visitors

  # devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: 'registrations' } do
    match 'users/sign_out', to: 'devise/sessions#destroy', via: :delete
  end
  resources :users do
    match '/new_gallery', to: 'users#new_gallery', via: :get
    match '', to: 'users#create_gallery', via: :patch
  end

  resources :attachments do
    member do
      post 'like'
      post 'dislike'
    end
  end
  get 'all_attachments', to: 'attachments#all_attachments'
  get '/:id/show_gallery', to: 'attachments#show_gallery', as: 'gallery'
  resources :roles
  resources :orders
  get '/orders/confirm_order', to: 'orders#confirm_order'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
 <li><%= link_to 'Home', root_path %></li>
 <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? && current_user.admin? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'my profile', user_path(current_user) %></li>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'User Roles', roles_path %></li>
  <li><%= link_to 'My Attachments', attachments_path %></li>
  <li><%= link_to 'All Attachments', all_attachments_path %></li>
  <li><%= link_to 'Log out', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to 'Admin Panel', admin_root_path %></li>
<% elsif user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'My Attachments', attachments_path %></li>
  <li><%= link_to 'All Attachments', all_attachments_path %></li>
  <li><%= link_to 'my profile', user_path(current_user) %></li>
  <li><%= link_to 'Log out', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to 'Admin Panel', admin_root_path %></li>
<% else  %>
  <li><%= link_to 'All Attachments', all_attachments_path %></li>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Image Gallery" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Image Gallery" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag "nested_form" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>